<?php
/**
 * Plugin Name: WP Update Dashboard
 * Description: Displays the cached WordPress update policy status generated by the external updater scripts.
 * Version: 0.1.0
 * Author: HFE
 */

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

const WPUD_STATUS_JSON = 'update-status.json';
const WPUD_MAX_STATUS_AGE = 86400;

add_action('wp_dashboard_setup', 'wpud_register_dashboard_widget');
add_action('admin_enqueue_scripts', 'wpud_enqueue_admin_styles');

function wpud_register_dashboard_widget(): void
{
    if (!current_user_can('update_plugins')) {
        return;
    }

    wp_add_dashboard_widget(
        'wpud_update_dashboard',
        'WordPress Update Status',
        'wpud_render_dashboard_widget'
    );

    wpud_place_dashboard_widget_after_site_health();
}

function wpud_place_dashboard_widget_after_site_health(): void
{
    global $wp_meta_boxes;

    if (!isset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_site_health'], $wp_meta_boxes['dashboard']['normal']['core']['wpud_update_dashboard'])) {
        return;
    }

    $coreWidgets = $wp_meta_boxes['dashboard']['normal']['core'];
    $updateWidget = $coreWidgets['wpud_update_dashboard'];
    unset($coreWidgets['wpud_update_dashboard']);

    $orderedWidgets = [];
    foreach ($coreWidgets as $widgetId => $widget) {
        $orderedWidgets[$widgetId] = $widget;

        if ($widgetId === 'dashboard_site_health') {
            $orderedWidgets['wpud_update_dashboard'] = $updateWidget;
        }
    }

    $wp_meta_boxes['dashboard']['normal']['core'] = $orderedWidgets;
}

function wpud_enqueue_admin_styles(string $hook): void
{
    if ($hook !== 'index.php') {
        return;
    }

    wp_register_style('wpud-admin', false, [], '0.1.0');
    wp_enqueue_style('wpud-admin');
    wp_add_inline_style('wpud-admin', wpud_admin_css());
}

function wpud_render_dashboard_widget(): void
{
    $status = wpud_load_status();

    if (!$status['ok']) {
        echo '<p class="wpud-muted">' . esc_html($status['message']) . '</p>';
        return;
    }

    $data = $status['data'];
    $counts = is_array($data['counts'] ?? null) ? $data['counts'] : [];
    $groups = is_array($data['groups'] ?? null) ? $data['groups'] : [];
    $generatedAt = (string) ($data['generated_at'] ?? '');
    $summary = (string) ($data['summary'] ?? 'no updates');
    $isStale = wpud_is_stale($generatedAt);

    echo '<div class="wpud-status">';
    echo '<div class="wpud-summary">';
    echo '<strong>' . esc_html(ucfirst($summary)) . '</strong>';
    echo '<span>' . esc_html(wpud_generated_label($generatedAt, $isStale)) . '</span>';
    echo '</div>';

    if ($isStale) {
        echo '<p class="wpud-warning">This status file is stale. Check that the external update cron is running.</p>';
    }

    echo '<div class="wpud-counts">';
    wpud_render_count('Emergency', (int) ($counts['emergency_update'] ?? 0), 'danger');
    wpud_render_count('Manual review', (int) ($counts['manual_review'] ?? 0), 'warning');
    wpud_render_count('Normal', (int) ($counts['normal_update'] ?? 0), 'ok');
    wpud_render_count('Pending', (int) ($counts['emergency_waiting'] ?? 0) + (int) ($counts['normal_waiting'] ?? 0), 'muted');
    echo '</div>';

    wpud_render_group('Emergency updates', $groups['emergency_action'] ?? []);
    wpud_render_group('Emergency pending', $groups['emergency_waiting'] ?? []);
    wpud_render_group('Normal updates', $groups['normal_action'] ?? []);
    wpud_render_group('Normal pending', $groups['normal_waiting'] ?? []);
    wpud_render_group('Manual review', $groups['manual_review'] ?? []);

    echo '</div>';
}

function wpud_load_status(): array
{
    $path = wpud_status_json_path();
    if (!is_file($path)) {
        return [
            'ok' => false,
            'message' => 'No updates available yet, if this continues for another day tell Matt!',
        ];
    }

    $cacheKey = 'wpud_status_' . md5($path . '|' . (string) filemtime($path));
    $cached = get_transient($cacheKey);
    if (is_array($cached)) {
        return ['ok' => true, 'data' => $cached];
    }

    $json = file_get_contents($path);
    if ($json === false || trim($json) === '') {
        return [
            'ok' => false,
            'message' => 'The update status file could not be read.',
        ];
    }

    $data = json_decode($json, true);
    if (!is_array($data) || (int) ($data['schema_version'] ?? 0) !== 1) {
        return [
            'ok' => false,
            'message' => 'The update status file is invalid or uses an unsupported schema.',
        ];
    }

    set_transient($cacheKey, $data, 300);
    return ['ok' => true, 'data' => $data];
}

function wpud_status_json_path(): string
{
    $path = plugin_dir_path(__FILE__) . WPUD_STATUS_JSON;

    if (defined('WPUD_STATUS_JSON_PATH')) {
        $path = (string) constant('WPUD_STATUS_JSON_PATH');
    }

    return (string) apply_filters('wpud_status_json_path', $path);
}

function wpud_render_count(string $label, int $count, string $tone): void
{
    echo '<div class="wpud-count wpud-count-' . esc_attr($tone) . '">';
    echo '<span>' . esc_html((string) $count) . '</span>';
    echo '<small>' . esc_html($label) . '</small>';
    echo '</div>';
}

function wpud_render_group(string $heading, $items): void
{
    if (!is_array($items) || $items === []) {
        return;
    }

    echo '<div class="wpud-group">';
    echo '<h3>' . esc_html($heading) . '</h3>';
    echo '<ul>';
    foreach ($items as $item) {
        if (!is_array($item)) {
            continue;
        }

        echo '<li>';
        echo '<strong>' . esc_html((string) ($item['slug'] ?? '')) . '</strong>';
        echo '<span>' . esc_html(wpud_item_version_text($item)) . '</span>';
        if (!empty($item['note'])) {
            echo '<em>' . esc_html((string) $item['note']) . '</em>';
        }
        echo '</li>';
    }
    echo '</ul>';
    echo '</div>';
}

function wpud_item_version_text(array $item): string
{
    $current = (string) ($item['current_version'] ?? '');
    $target = (string) ($item['target_version'] ?? '');

    if ($target === '') {
        return $current;
    }

    return $current . ' -> ' . $target;
}

function wpud_generated_label(string $generatedAt, bool $isStale): string
{
    if ($generatedAt === '') {
        return 'Generated time unavailable';
    }

    $timestamp = strtotime($generatedAt);
    if ($timestamp === false) {
        return 'Generated time invalid';
    }

    $label = 'Generated ' . human_time_diff($timestamp, time()) . ' ago';
    return $isStale ? $label . ' - stale' : $label;
}

function wpud_is_stale(string $generatedAt): bool
{
    $timestamp = strtotime($generatedAt);
    if ($timestamp === false) {
        return true;
    }

    return (time() - $timestamp) > WPUD_MAX_STATUS_AGE;
}

function wpud_admin_css(): string
{
    return '
        #wpud_update_dashboard .inside { margin: 0; padding: 12px; }
        .wpud-summary { display: flex; justify-content: space-between; gap: 12px; align-items: baseline; margin-bottom: 12px; }
        .wpud-summary strong { font-size: 15px; }
        .wpud-summary span, .wpud-muted { color: #646970; }
        .wpud-warning { margin: 8px 0 12px; color: #8a4b00; }
        .wpud-counts { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 8px; margin-bottom: 12px; }
        .wpud-count { border: 1px solid #dcdcde; border-left-width: 4px; padding: 8px; background: #fff; }
        .wpud-count span { display: block; font-size: 20px; font-weight: 600; line-height: 1.1; }
        .wpud-count small { color: #646970; }
        .wpud-count-danger { border-left-color: #d63638; }
        .wpud-count-warning { border-left-color: #dba617; }
        .wpud-count-ok { border-left-color: #00a32a; }
        .wpud-count-muted { border-left-color: #72aee6; }
        .wpud-group { border-top: 1px solid #dcdcde; padding-top: 10px; margin-top: 10px; }
        .wpud-group h3 { font-size: 13px; margin: 0 0 6px; }
        .wpud-group ul { margin: 0; }
        .wpud-group li { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 8px; margin: 0; padding: 5px 0; }
        .wpud-group li strong { overflow-wrap: anywhere; }
        .wpud-group li span { color: #50575e; white-space: nowrap; }
        .wpud-group li em { grid-column: 1 / -1; color: #646970; font-style: normal; }
        @media (max-width: 782px) {
            .wpud-counts { grid-template-columns: repeat(2, minmax(0, 1fr)); }
            .wpud-summary { display: block; }
        }
    ';
}
